apiVersion: v1
kind: Pod
metadata:
  name: mysql
  #namespace: tindd-study
  labels:
    app: mysql
    env: test
    version: 1.0.0
    component: db
spec:
  containers:
  - name: mysql
    image: mysql:5.7.38
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: password
    # resources:
    #   limits:
    #     cpu: 200m
    #     memory: 500Mi
    #   requests:
    #     cpu: 100m
    #     memory: 200Mi
    ports:
    - containerPort: 3306
