apiVersion: v1
items:
- apiVersion: v1
  kind: Node
  metadata:
    annotations:
      kubeadm.alpha.kubernetes.io/cri-socket: unix:///var/run/cri-dockerd.sock
      node.alpha.kubernetes.io/ttl: "0"
      volumes.kubernetes.io/controller-managed-attach-detach: "true"
    creationTimestamp: "2022-08-20T14:23:33Z"
    labels:
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/os: linux
      kubernetes.io/arch: amd64
      kubernetes.io/hostname: tindd-cluster
      kubernetes.io/os: linux
      minikube.k8s.io/commit: 62e108c3dfdec8029a890ad6d8ef96b6461426dc
      minikube.k8s.io/name: tindd-cluster
      minikube.k8s.io/primary: "true"
      minikube.k8s.io/updated_at: 2022_08_20T21_23_37_0700
      minikube.k8s.io/version: v1.26.1
      node-role.kubernetes.io/control-plane: ""
      node.kubernetes.io/exclude-from-external-load-balancers: ""
    name: tindd-cluster
    resourceVersion: "2515"
    uid: 466b1740-736e-459e-856e-848d8ce779f7
  spec:
    podCIDR: 10.244.0.0/24
    podCIDRs:
    - 10.244.0.0/24
  status:
    addresses:
    - address: 192.168.58.2
      type: InternalIP
    - address: tindd-cluster
      type: Hostname
    allocatable:
      cpu: "2"
      ephemeral-storage: 61255492Ki
      hugepages-1Gi: "0"
      hugepages-2Mi: "0"
      memory: 4029192Ki
      pods: "110"
    capacity:
      cpu: "2"
      ephemeral-storage: 61255492Ki
      hugepages-1Gi: "0"
      hugepages-2Mi: "0"
      memory: 4029192Ki
      pods: "110"
    conditions:
    - lastHeartbeatTime: "2022-08-20T15:14:48Z"
      lastTransitionTime: "2022-08-20T14:23:28Z"
      message: kubelet has sufficient memory available
      reason: KubeletHasSufficientMemory
      status: "False"
      type: MemoryPressure
    - lastHeartbeatTime: "2022-08-20T15:14:48Z"
      lastTransitionTime: "2022-08-20T14:23:28Z"
      message: kubelet has no disk pressure
      reason: KubeletHasNoDiskPressure
      status: "False"
      type: DiskPressure
    - lastHeartbeatTime: "2022-08-20T15:14:48Z"
      lastTransitionTime: "2022-08-20T14:23:28Z"
      message: kubelet has sufficient PID available
      reason: KubeletHasSufficientPID
      status: "False"
      type: PIDPressure
    - lastHeartbeatTime: "2022-08-20T15:14:48Z"
      lastTransitionTime: "2022-08-20T14:23:48Z"
      message: kubelet is posting ready status
      reason: KubeletReady
      status: "True"
      type: Ready
    daemonEndpoints:
      kubeletEndpoint:
        Port: 10250
    images:
    - names:
      - k8s.gcr.io/etcd@sha256:13f53ed1d91e2e11aac476ee9a0269fdda6cc4874eba903efd40daf50c55eee5
      - k8s.gcr.io/etcd:3.5.3-0
      sizeBytes: 299495233
    - names:
      - k8s.gcr.io/kube-apiserver@sha256:a04609b85962da7e6531d32b75f652b4fb9f5fe0b0ee0aa160856faad8ec5d96
      - k8s.gcr.io/kube-apiserver:v1.24.3
      sizeBytes: 129710737
    - names:
      - k8s.gcr.io/kube-controller-manager@sha256:f504eead8b8674ebc9067370ef51abbdc531b4a81813bfe464abccb8c76b6a53
      - k8s.gcr.io/kube-controller-manager:v1.24.3
      sizeBytes: 119360464
    - names:
      - k8s.gcr.io/kube-proxy@sha256:c1b135231b5b1a6799346cd701da4b59e5b7ef8e694ec7b04fb23b8dbe144137
      - k8s.gcr.io/kube-proxy:v1.24.3
      sizeBytes: 109939784
    - names:
      - k8s.gcr.io/kube-scheduler@sha256:e199523298224cd9f2a9a43c7c2c37fa57aff87648ed1e1de9984eba6f6005f0
      - k8s.gcr.io/kube-scheduler:v1.24.3
      sizeBytes: 50989989
    - names:
      - k8s.gcr.io/coredns/coredns@sha256:5b6ec0d6de9baaf3e92d0f66cd96a25b9edbce8716f5f15dcd1a616b3abd590e
      - k8s.gcr.io/coredns/coredns:v1.8.6
      sizeBytes: 46829283
    - names:
      - gcr.io/k8s-minikube/storage-provisioner@sha256:18eb69d1418e854ad5a19e399310e52808a8321e4c441c1dddad8977a0d7a944
      - gcr.io/k8s-minikube/storage-provisioner:v5
      sizeBytes: 31465472
    - names:
      - k8s.gcr.io/pause@sha256:bb6ed397957e9ca7c65ada0db5c5d1c707c9c8afc80a94acbe69f3ae76988f0c
      - k8s.gcr.io/pause:3.7
      sizeBytes: 711184
    - names:
      - k8s.gcr.io/pause@sha256:3d380ca8864549e74af4b29c10f9cb0956236dfb01c40ca076fb6c37253234db
      - k8s.gcr.io/pause:3.6
      sizeBytes: 682696
    nodeInfo:
      architecture: amd64
      bootID: 0aa19e3b-ae1d-4ff2-a68c-4753e80bd77f
      containerRuntimeVersion: docker://20.10.17
      kernelVersion: 5.10.104-linuxkit
      kubeProxyVersion: v1.24.3
      kubeletVersion: v1.24.3
      machineID: 4c192b04687c403f8fbb9bc7975b21b3
      operatingSystem: linux
      osImage: Ubuntu 20.04.4 LTS
      systemUUID: e44b2228-8a3d-46bc-8cdd-76509fb89fa8
kind: List
metadata:
  resourceVersion: ""