apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  #namespace: tindd-study
spec:
  selector:
    app: nginx      #match lable pod
  # type: ClusterIP
  # sessionAffinity: None
  # sessionAffinityConfig:
  #   clientIP:
  #     timeoutSeconds: 10800
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
  type: NodePort