apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-192-168-57-163.ap-southeast-1.compute.internal
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: /home/tindd-aws
            name: tindd-aws
      - name: alpine
        image: alpine
        command:
          - "/bin/sh"
          - "-c"
        args:
          - "tail -f /dev/null"
        volumeMounts:
          - mountPath: /dala/tindd-aws
            name: tindd-aws
      volumes:
        - name: tindd-aws
          persistentVolumeClaim:
            claimName: tindd-pvc