apiVersion: v1
kind: PersistentVolume
metadata:
  name: tindd-pv 
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: ""
  awsElasticBlockStore:
    volumeID: vol-01a6787a3aae6d95c