apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  # strategy:
  #   type: Recreate
  selector:
    matchLabels:
      app: nginx
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "0.1"
            memory: 50Mi
          limits:
            cpu: "0.5"
            memory: 200Mi