apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 5
          successThreshold: 1
          failureThreshold: 5
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - "/bin/sh"
              - "-c"
              - "cat /usr/share/nginx/html/index.html"
          initialDelaySeconds: 5
          successThreshold: 5
          failureThreshold: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: "0.1"
            memory: 50Mi
          limits:
            cpu: "0.5"
            memory: 200Mi