apiVersion: v1
kind: Pod
metadata:
  name: java
  labels:
    app: java
    env: test
    version: 1.0.1
    component: be
spec:
  containers:
  - name: java
    image: openjdk:11
    command:
      - "/bin/sh"
      - "-c"
    args:
      - "tail -f /dev/null"
    # resources:
    #   limits:
    #     cpu: 200m
    #     memory: 500Mi
    #   requests:
    #     cpu: 100m
    #     memory: 200Mi
    ports:
    - containerPort: 8080
