apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: db
    env: test
    version: 1.0.0
    component: db
spec:
  containers:
  - name: mysql
    image: mysql:5.7.38
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: password
    ports:
    - containerPort: 3306
