apiVersion: v1
kind: Pod
metadata:
  name: nginx-frontend
  labels:
    env: prod
    app: nginx
    version: 1.0.0
spec:
  containers:
    - name: nginx
      image: nginx:1.7.9
      resources:
        requests:
          cpu: "200m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "500Mi"
      ports:
        - containerPort: 80