apiVersion: v1
kind: Pod
metadata:
  name: pod-test
  labels:
    name: test
spec:
  nodeSelector:
    kubernetes.io/hostname: minikube-m02
  containers:
  - name: test
    image: alpine:latest
    command:
      - "/bin/sh"
      - "-c"
    args:
      - "tail -f /dev/null"
    # resources:
    #   limits:
    #     cpu: 200m
    #     memory: 500Mi
    #   requests:
    #     cpu: 100m
    #     memory: 200Mi
    # ports:
    # - containerPort: 8080
