apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "configmap.fullname" . }}
data:
    techmaster_1: {{ .Values.techmaster.techmaster_1 | quote }}
    techmaster_2: {{ default "test" .Values.techmaster.techmaster_2 | quote }}