apiVersion: rbac.authorization.k8s.io/v1 
kind: Role
metadata:
 namespace: techmaster
 name: service-reader 
rules:
  - apiGroups: [""]
    verbs: ["get", "list"] 
    resources: ["pods"]
---
apiVersion: rbac.authorization.k8s.io/v1 
kind: RoleBinding
metadata:
 name: service-reader
 namespace: techmaster 
roleRef:
 apiGroup: rbac.authorization.k8s.io 
 kind: Role
 name: service-reader
subjects:
 - kind: ServiceAccount # Kind is User or ServiceAccount
   name: techmaster # name of the SA 
   namespace: techmaster